on:
  push:
    branches:
      - master







jobs:
  bulid:
    runs-on: ubuntu-latest
    
    steps:
      - name: "print all folder"
        run: ls
      
      
      - uses: action checkout@v3
      
      - name: "print all folder"
        run: ls

     
        
